"""
File: gemini_reviewer.py

Purpose:
    Provides AI-powered semantic validation for generated FormIQ forms.

What this file does:
    - Sends a generated form to Gemini for semantic review.
    - Detects issues that deterministic validation may miss.
    - Checks ambiguity, double-barrelled questions, bias,
      missing context, poor answer options, and relevance.
    - Returns a structured semantic validation result.

Important:
    This service does NOT create or modify Google Forms.

Architecture:
    GeneratedForm
        ↓
    Gemini Semantic Reviewer
        ↓
    SemanticValidationResult
        ↓
    Form Quality Engine
"""

import json
import re

from dotenv import load_dotenv
from google import genai

from app.schemas.form import GeneratedForm
from app.schemas.validation import (
    SemanticValidationResult,
)


load_dotenv()


def get_gemini_client():
    """
    Create and return the Gemini client using the API key
    configured in the FormIQ .env file.
    """

    import os

    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        raise ValueError(
            "GEMINI_API_KEY is not configured in .env"
        )

    return genai.Client(
        api_key=api_key
    )


def clean_json_response(raw_output: str) -> str:
    """
    Clean Gemini's response before JSON parsing.

    Gemini may sometimes return JSON inside a Markdown
    code fence such as:

        ```json
        {
            ...
        }
        ```

    json.loads() cannot parse those Markdown markers.

    This function removes the code fence and returns
    the actual JSON content.
    """

    if not raw_output:
        raise ValueError(
            "Gemini returned an empty response."
        )

    cleaned = raw_output.strip()

    # Remove ```json ... ``` wrapper.
    cleaned = re.sub(
        r"^```json\s*",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )

    cleaned = re.sub(
        r"^```\s*",
        "",
        cleaned,
    )

    cleaned = re.sub(
        r"\s*```$",
        "",
        cleaned,
    )

    return cleaned.strip()


def review_form_semantically(
    form: GeneratedForm,
    requirement: str = "",
) -> SemanticValidationResult:
    """
    Review the generated form using Gemini.

    Gemini evaluates semantic and usability aspects that
    deterministic validators may not detect.
    """

    client = get_gemini_client()

    questions = []

    for index, question in enumerate(
        form.questions,
        start=1,
    ):
        questions.append(
            {
                "number": index,
                "title": question.title,
                "type": question.type,
                "required": question.required,
                "options": question.options,
            }
        )

    prompt = f"""
You are a senior survey and form quality expert.

You are reviewing a form generated by an AI system called FormIQ.

Your job is NOT to redesign the entire form.

Your job is to identify semantic and usability problems
that deterministic rule-based validation may not detect.

USER REQUIREMENT:
{requirement}

GENERATED FORM:
{json.dumps(questions, indent=2)}

Check for:

1. Ambiguous questions
2. Double-barrelled questions
3. Leading questions
4. Biased wording
5. Unclear wording
6. Overly complex wording
7. Inappropriate question type
8. Missing context
9. Poor answer options
10. Questions that do not appear relevant to the requirement

IMPORTANT:

- Do not invent problems.
- Do not flag a question merely because it asks for an email.
- Do not consider normal demographic/contact fields automatically problematic.
- Only report meaningful issues.
- Give practical suggestions for improvement.
- Score the semantic quality from 0 to 100.

OUTPUT REQUIREMENTS:

Return ONLY valid JSON.

DO NOT use Markdown.
DO NOT wrap the JSON inside ```json.
DO NOT add explanations before or after the JSON.

Use exactly this structure:

{{
    "semantic_score": 95,
    "issues": [
        {{
            "category": "Double-Barrelled",
            "severity": "WARNING",
            "message": "The question asks about two different things.",
            "question": "Example question",
            "suggestion": "Split this into two separate questions."
        }}
    ],
    "strengths": [
        "Questions are generally clear.",
        "Question types are appropriate."
    ]
}}
"""

    response = client.interactions.create(
        model="gemini-3.6-flash",
        input=prompt,
    )

    raw_output = response.output_text

    cleaned_output = clean_json_response(
        raw_output
    )

    try:

        data = json.loads(
            cleaned_output
        )

        return SemanticValidationResult.model_validate(
            data
        )

    except json.JSONDecodeError as e:

        raise ValueError(
            "Gemini semantic reviewer returned "
            f"invalid JSON: {e}\n"
            f"Cleaned response: {cleaned_output}"
        )

    except Exception as e:

        raise ValueError(
            "Semantic validation failed: "
            f"{e}\n"
            f"Cleaned response: {cleaned_output}"
        )