"""
File: form.py

Purpose:
    Defines the Pydantic data models used by FormIQ for form generation,
    form questions, and API request/response validation.

What this file does:
    - Defines the structure of an individual form question.
    - Defines the structure of a generated form.
    - Ensures AI-generated form data follows a predictable schema.

Architecture:
    Gemini
        ↓
    GeneratedForm
        ↓
    Validation
        ↓
    Google Forms / API Response

This file contains data schemas only.
It does not contain business logic or API calls.
"""

from typing import List, Optional

from pydantic import BaseModel


class FormQuestion(BaseModel):
    """
    Represents one question inside a FormIQ form.
    """

    title: str
    type: str
    required: bool = False
    options: Optional[List[str]] = None


class GeneratedForm(BaseModel):
    """
    Represents the complete form generated by FormIQ.
    """

    title: str
    description: str
    questions: List[FormQuestion]